const { execFileSync, spawnSync } = require("child_process");
const { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } = require("fs");
const os = require("os");
const path = require("path");

const root = path.resolve(__dirname, "..");
const version = require(path.join(root, "package.json")).version;
const vsix = path.join(root, "dist", `lewisl.wipstream-${version}.vsix`);

function git(cwd, args) {
  return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}

function configureIdentity(directory) {
  git(directory, ["config", "user.name", "WipStream Live Test"]);
  git(directory, ["config", "user.email", "wipstream-live@example.invalid"]);
}

function usage() {
  console.log("Usage:");
  console.log("  npm run test:live");
  console.log("  npm run test:live:verify -- /private/tmp/wipstream-live-...");
  console.log("  npm run test:live:cleanup -- /private/tmp/wipstream-live-...");
}

function requireRunDirectory(argument) {
  if (!argument || !existsSync(argument)) {
    throw new Error("Provide the preserved live-test directory printed by npm run test:live.");
  }
  return path.resolve(argument);
}

function verify(runDirectory) {
  const remote = path.join(runDirectory, "remote.git");
  const first = path.join(runDirectory, "first");
  const second = path.join(runDirectory, "second");
  const refs = git(remote, ["show-ref"]).split("\n");
  if (refs.some((line) => /refs\/heads\/(feature|wip\/feature)$/.test(line))) {
    throw new Error("Temporary feature branches remain. Run WipStream: To Main in the second isolated window first.");
  }
  const work = git(remote, ["show", "main:live-work.txt"]);
  if (work !== "first computer\nsecond computer") {
    throw new Error(`Unexpected live-work.txt content on remote main: ${JSON.stringify(work)}`);
  }
  const firstMain = git(first, ["rev-parse", "main"]);
  const remoteMain = git(remote, ["rev-parse", "main"]);
  const secondMain = git(second, ["rev-parse", "main"]);
  if (firstMain !== remoteMain || secondMain !== remoteMain) {
    throw new Error("Both clones must be updated to the completed remote main branch.");
  }
  const firstBranches = git(first, ["branch", "--format=%(refname:short)"]).split("\n");
  if (firstBranches.includes("feature") || firstBranches.includes("wip/feature")) {
    throw new Error("Resume on the first computer did not remove the completed temporary branches.");
  }
  console.log(`Live extension test passed for ${runDirectory}.`);
  console.log("Both computers now show completed main; the next feature begins with WipStream: Initialize Stream.");
}

function cleanup(runDirectory) {
  const resolved = requireRunDirectory(runDirectory);
  if (!path.basename(resolved).startsWith("wipstream-live-")) {
    throw new Error("Refusing to remove a directory that is not a WipStream live-test fixture.");
  }
  rmSync(resolved, { recursive: true, force: true });
  console.log(`Removed ${resolved}.`);
}

function seedInstructions() {
  return `# WipStream live extension test

This workspace is disposable. It uses a private bare remote at the parent test directory and an isolated WipStream installation.

## First computer window

1. Open the Command Palette and run **WipStream: Initialize Stream**. Accept the four defaults.
2. Confirm it reports that **Get Current from Remote** completed and that you are editing \`wip/feature\`.
3. Create \`live-work.txt\` with exactly this first line: \`first computer\`.
4. Run **WipStream: Save to Remote**. Confirm it reports a synced checkpoint.
5. Run **WipStream: To Feature**.

## Second computer window

1. Run **WipStream: Initialize Stream**. It should attach to the existing stream.
2. Confirm it reports that **Get Current from Remote** completed and that \`live-work.txt\` has the first-computer line.
3. Append exactly: \`second computer\`.
4. Run **WipStream: Save to Remote**, then **WipStream: To Feature**, then **WipStream: To Main**.

## Back on the first computer

1. Run **WipStream: Get Current from Remote**. Confirm its message says that another computer completed the feature and that \`main\` is current.
2. Confirm the temporary branches are gone locally. Do not initialize another stream; verification checks this completed-stream state.

Do not edit this file. It is part of the seeded main branch so WipStream initialization can require a clean worktree.
`;
}

function launchLiveTest() {
  if (!existsSync(vsix)) {
    throw new Error(`Expected VSIX is missing: ${vsix}. Run npm run package first.`);
  }

  const runDirectory = mkdtempSync(path.join(os.tmpdir(), "wipstream-live-"));
  const profile = path.join(runDirectory, "profile");
  const extensions = path.join(runDirectory, "extensions");
  const remote = path.join(runDirectory, "remote.git");
  const seed = path.join(runDirectory, "seed");
  const first = path.join(runDirectory, "first");
  const second = path.join(runDirectory, "second");

  git(runDirectory, ["init", "--bare", remote]);
  git(runDirectory, ["init", seed]);
  configureIdentity(seed);
  writeFileSync(path.join(seed, "LIVE_TEST.md"), seedInstructions());
  writeFileSync(path.join(seed, "README.md"), "WipStream live-test fixture\n");
  git(seed, ["add", "LIVE_TEST.md", "README.md"]);
  git(seed, ["commit", "-m", "Seed live test fixture"]);
  git(seed, ["branch", "-M", "main"]);
  git(seed, ["remote", "add", "origin", remote]);
  git(seed, ["push", "-u", "origin", "main"]);
  git(remote, ["symbolic-ref", "HEAD", "refs/heads/main"]);
  git(runDirectory, ["clone", remote, first]);
  git(runDirectory, ["clone", remote, second]);
  configureIdentity(first);
  configureIdentity(second);

  const install = spawnSync(
    "code",
    ["--user-data-dir", profile, "--extensions-dir", extensions, "--install-extension", vsix, "--force"],
    { stdio: "inherit" }
  );
  if (install.status !== 0) {
    throw new Error("VS Code could not install WipStream into the isolated live-test profile.");
  }

  for (const directory of [first, second]) {
    const launch = spawnSync(
      "code",
      [
        "--new-window",
        "--user-data-dir",
        profile,
        "--extensions-dir",
        extensions,
        "--disable-workspace-trust",
        directory,
      ],
      { stdio: "inherit" }
    );
    if (launch.status !== 0) {
      throw new Error(`VS Code could not open the isolated test workspace ${directory}.`);
    }
  }

  console.log("\nOpened two isolated VS Code windows. The primary Codex window and extension profile were not used.");
  console.log(`Live-test root: ${runDirectory}`);
  console.log(`Isolated VS Code profile: ${profile}`);
  console.log(`Isolated extensions directory: ${extensions}`);
  console.log("Follow LIVE_TEST.md in the two opened windows. When complete, run:");
  console.log(`  npm run test:live:verify -- ${runDirectory}`);
  console.log("Keep the fixture until verification passes; then remove it with:");
  console.log(`  npm run test:live:cleanup -- ${runDirectory}`);
}

try {
  const [mode, argument] = process.argv.slice(2);
  if (!mode) {
    launchLiveTest();
  } else if (mode === "--verify") {
    verify(requireRunDirectory(argument));
  } else if (mode === "--cleanup") {
    cleanup(argument);
  } else {
    usage();
    process.exitCode = 1;
  }
} catch (error) {
  console.error(error.stack || error);
  process.exitCode = 1;
}
